### ISSUE TITLE
Log stream events expiration: never

### ISSUE THREAD

**Issue by fabiocognigni** [gilt/nova#33]
The below nova.yml config snippet creates log streams with **events that never expires** .

It'd be nice to have the ability to configure this in Nova or set a different default (e.g. 30 days).

```
logs:
  - file: /var/log/messages
    group_name: my-app-name-syslog
    datetime_format: '%b %m %H:%M:%S'
  - file: /var/log/my-app-name/application.log
    group_name: my-app-name-application
    datetime_format: '%Y-%m-%d %H:%M:%S,%f'
```
